---
name: Gate
on:
    pull_request:
        branches: [ 'master', ]

jobs:
    build-blog:
        name: Build Blog
        runs-on: ubuntu-latest
        container:
            image: fedora:latest
        steps:
            -   name: Install Dependencies
                run: dnf install -y ruby rubygem-bundler ruby-devel libffi libffi-devel @"Development Tools" gcc-c++
            -   name: Checkout
                uses: actions/checkout@v3
            -   name: Install Ruby Dependencies
                run: bundle install -j2
            -   name: Build
                run: bundle exec jekyll build

